### ISSUE TITLE
Password protection for viewing the video stream

### ISSUE THREAD

**Issue by mysteryman386** [easytarget/esp32-cam-webserver#121] opened 2021-06-04 03:27 UTC
Hi,
I tried this ESP32 Cam software, and I want to actually use this as a ip surveillance camera in conjuction with my NAS, but one thing that bars me from using the ESP32 cam as a surveillance cam is the lack of security for accessing the video stream. I would love to have this feature implemented!

**Comment by easytarget** [comment] 2021-06-07 14:24
Duplicate of #54 : Out of scope

**Closed by easytarget** 2021-06-07 14:24 UTC
